platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.3.0

inputs:
- name: flight-school

run:
  path: tar
  args: ["cvzf", "flight-school.tgz", "flight-school/"]