platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.3.0

inputs:
- name: flight-school
- name: version
outputs:
- name: build

run:
  path: tar
  args: ["cvzf", "build/flight-school-$(cat version/version).tgz", "flight-school/"]
