resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/grosendorf/flight-school
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/ci/test.yml

- name: build
  plan:
  - get: flight-school
    trigger: true
    passed: [test-app]
  - task: build
    file: flight-school/ci/build.yml