resources:
- name: flight-school
  type: git
  source:
    uri: https://github.com/grosendorf/flight-school
    branch: master
- name: release-bucket
  type: s3
  source:
    bucket: devco-concourse-demo
    region_name: us-east-1
    regexp: flight-school-(.*).tgz
    access_key_id: {{access}}
    secret_access_key: {{secret}}
- name: version
  type: semver
  source:
    bucket: devco-concourse-demo
    region_name: us-east-1
    key: VERSION
    access_key_id: {{access}}
    secret_access_key: {{secret}}
    initial_version: 1.0.0

jobs:
- name: test-23
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/ci/test23.yml
- name: test-22
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/ci/test22.yml

- name: build
  plan:
  - get: version
    params:
      bump: patch
  - get: flight-school
    trigger: true
    passed: [test-23, test-22]
  - task: build
    file: flight-school/ci/build.yml
  - put: release-bucket
    params:
      file: build/flight-school-*.tgz
      acl: private
  - put: version
    params: {file: version/version}
